- README.md
Just the facts. And a picture. With a few links. And thankyous. And a license or three.
> feat(readme) init

- bindings/rust/proton-sys/lib.rs
Per Boscops self-raised, but never merged issue
https://doc.rust-lang.org/nomicon/ffi.html#representing-opaque-structs
Basically removes potentially undefined behavior
> fix(ffi) define struct

- bindings/rust/proton-sys/lib.rs
- templates/rust/Cargo.toml
- templates/rust/src/main.rs
`Serverless` mode is available for production builds, and the Rust webserver is now not required. However, secure Web APIs are still a topic to be investigated, probably this won't support them, so it's going to be optional and recommended for simple applications. The main goal os the serverless mode is to make the application more secure.
> chore(merge) feature/serverless

- lib/rust/Cargo.toml
- lib/rust/build.rs
- lib/rust/src/app.rs
- lib/rust/src/app/runner.rs
- lib/rust/src/lib.rs
- lib/rust/src/server.rs
- templates/rust/Cargo.toml
- templates/rust/src/main.rs
> feat(tauri) core template isolated

- lib/rust/src/app.rs
- lib/rust/src/app/runner.rs
- lib/rust/src/config.rs
- lib/rust/src/event.rs
- lib/rust/src/lib.rs
- lib/rust/src/salt.rs
There's an edge case for how the webview and our embeddedServer loads its URLs.
When the config -> host is set to something like `localhost` or `127.0.0.1` (without http:// protocol), the server starts correctly, but the webview doesn't. We have to explicitely set the http protocol on the webview, but not on the embedded web server.
So, with this PR, we add the protocol for the webview load URL if its not there, and we always remove it from the config host. With this approach, the embedded web server MUST be served locally.
There are some …
> fix(tauri) embedded-server edge case with config host

- .github/workflows/test-on-pr.yml
It has been hanging on MacOS builds. Although we would want to fix this hang long term. This is a temporary way to deal with it and prevent future occurrences of swamping the CI. It would be surprising if jest tests ran longer than 15 minutes.
> set timeout on `yarn test` in Github Actions

- .github/workflows/test-on-pr.yml
Previously, the `build-tauri` job would fail on Ubuntu because `webkit2gtk` was not installed. This PR creates a separate job for Ubuntu which installs `webkit2gtk` before running the steps from `build-tauri`.
> fix(ci): install webkit2gtk on ubuntu before building

- cli/tauri.js/runner.js
If `distDir/index.html` cannot be found, print a helpful error message
Previously, a TypeError would occur
> feat(runner/build): add error message for missing dist

- .github/workflows/build-smoke-tests.yml
The `via-prod` jobs are silently failing on Ubuntu (somehow, GitHub Actions thinks that the job passed even though it [failed](https://github.com/tauri-apps/tauri/pull/187/checks?check_run_id=357905199#step:11:107)) because `webkit2gtk` isn't installed
> fix(ci): Install webkit2gtk on ubuntu when building smoke tests via prod

- examples/.gitignore
Compiling on windows downloads WixTools to src-tauri/WixTools folder.
We don't want that polluting our repo
> Created .gitignore to ignore WixTools

- examples/react/next.js/package.json
Made yarn build work as expected.
Proper command to export a static site is `next export`. See [here](https://nextjs.org/docs#usage)
- [ x] Bugfix
- [ x] No
- [x ] It's submitted to the `dev` branch and _not_ the `master` branch
> Corrected example: Changed next build to next export

- cli/tauri-cli/src/bundle/common.rs
Fixes #231 
Fixes #202 (already closed)
This should fix the issues where CI builds pass when they should actually fail (see above issues for context).
I was originally looking at the JS/TS side and wondered if `process.exit()` was causing processes to exit with `0`, but when I tried changing that the error was still not solved. After digging through the Rust side I came across these areas:
https://github.com/tauri-apps/tauri/blob/f800daaf442a5a6a6304b25f2b49c08963966e13/cli/tauri-cli/src/main.rs#L65-L68 …
> fix(bundler): Return nonzero exit code when errors occur

- examples/react/create-react-app/src-tauri/Cargo.toml
- examples/react/next.js/src-tauri/Cargo.toml
- examples/svelte/svelte-app/src-tauri/Cargo.toml
The examples, which are also used as tests to ensure PRs don't break builds, should depend on the latest version of Tauri instead of the one published on crates.io. Some of the examples currently depend on v0.2.0 instead of the latest one from source. This means that changes to tauri that could potentially break the example projects may go unnoticed until the next version is released.
> fix(examples): Ensure examples use tauri from source instead of crates.io

- cli/tauri.js/src/helpers/tauri-config.ts
- cli/tauri.js/src/runner.ts
- tauri/src/app/runner.rs
- tauri/src/config.rs
This allows the Rust side to read the correct config (the Node CLI manipulates the config from `tauri.conf.json`).
> feat(tauri) read config overriden by the node CLI

- README.md
This should resolve some challenges with understanding the parts of tauri, especially why there are multiple CLIs. Until we have a rust-only CLI, or naming convention should probably refer to the bundler everywhere.
Documentation
> chore(readme): rename rust cli to bundler

- .github/workflows/push-to-dev.yml
This will create a draft release with all of the changes since the last tag. We can use it for the "marketing" changes / changelog, where each package can then still get its own changelog file. The bulk of the configuration sits in the tauri-pps/.github repo.
Let me know if this is not how you want to go about things. Ideally I think it would be great if we can use changesets, but the current code won't be able to support our repo. I have commented on an issue in regards to the possibility. This is a bit of a stopgap, and still has value even …
> chore(workflow): add global release changelog

- cli/tauri-cli/src/bundle/dmg_bundle.rs
- cli/tauri-cli/src/bundle/settings.rs
- cli/tauri-cli/src/bundle/templates/bundle_dmg
- Fix `sips` command
- Copy `seticon` from templates folder
- Only `cp bg.png` if it exists
This should fix the script for now, but I think it could become difficult to maintain in the future. We might want to look into using a package such as [`create-dmg`](https://github.com/sindresorhus/create-dmgl) or [`node-appdmg`](https://github.com/LinusU/node-appdmg) instead
> fix(bundler): Fix DMG script

- renovate.json
This also groups these folders that PRs will be opened per folder rather than per dep (less noisy).
> only enable renovate for certain folders

- renovate.json
I've accidentally disabled renovate. We need to instead disable in a package rule per https://github.com/renovatebot/config-help/issues/86 .
> chore(renovate): top level disable completely turns it off

- cli/tauri-cli/src/bundle/osx_bundle.rs
- examples/vue/quasar-app/src-tauri/src/main.rs
There is an issue on OSX where the $PATH environments are not available to an APP if you open it from the Finder, although it does have the $PATH if you open it from the console. This PR enhances the Builder with a bootstrapping shell script that injects the $PATH, essentially invoking the App from a terminal. It adds approximately 200 bytes to the bundle size. :(
**Does this PR introduce a breaking change?** 
> feat(builder): enable OSX sidecar from finder

- .github/workflows/release-npm.yml
In projects that use Yarn, `yarn audit` should be used for dependency audits. Using `npm audit` will fail since Yarn projects do not have `npm-shrinkwrap.json` or `package-lock.json` files.
> fix(publish): Use `yarn audit` instead of `npm audit`

- .github/workflows/release-cargo.yml
We were missing the envs so tauri-core didn't publish. It is fine if every package has these envs. We shouldn't need to verify as we have already built many times prior, and the verification gets very odd with packages all being bumped and being interdependent (inception verification).
> fix(publish): cargo release: add envs and publishPath, don't verify

- .github/workflows/check-on-push.yml
- .github/workflows/release-cargo.yml
- .github/workflows/test-on-pr.yml
- tauri/src/app/runner.rs
This file is one folder deeper than the other files which reference this env. This env is a relative folder reference so we need to concat an extra folder traversal into it.
> fix(tauri): make github action envs absolute for extra path level in runner.rs

- cli/tauri.js/package.json
This will let CI runs of the publish command reduce verbosity. We use the output from the command in our release notes.
> chore(workflows): split up prepare into postinstall and prepublishOnly

- tauri/src/endpoints.rs
- tauri/src/endpoints/cmd.rs
We can reinject the tauri.js after reload, with the following:
```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script type="text/javascript">
if (window.tauri === void 0) {
window.external.invoke(JSON.stringify({cmd: 'reload'}));
}
</script>
</head>
<body>
</body>
</html>
```
> fix: #377 window.tauri is undefined upon reloading

- cli/tauri.js/.eslintrc.js
- cli/tauri.js/src/api/tauricon.ts
Resolves ESLint errors in `tauricon.ts` and disables [`@typescript-eslint/default-param-last`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/default-param-last.md) (I'm happy to re-enable it if desired)
> refactor(tauri.js): Fix ESLint errors in src/api/tauricon.ts

- cli/tauri.js/package.json
From [lint-staged's release notes](https://github.com/okonet/lint-staged/releases/tag/v10.0.0):
> Prior to version 10, tasks had to manually include `git add` as the final step. This behavior has been integrated into lint-staged itself in order to prevent race conditions with multiple tasks editing the same files. If lint-staged detects `git add` in task configurations, it will show a warning in the console. Please remove `git add` from your configuration after upgrading.
> fix(tauri.js): Remove redundant "git add" from lint-staged script

- cli/tauri-bundler/src/bundle/templates/main.wxs
This modifies the Wix xml template to add a start menu shortcut on install. I also reorganized a tad, and changed the registry root on the uninstall shortcut to be either user or system as msi can be either (which removes the existing warning we had).
This is also believed to be the last remaining item for the [guijs Windows build](https://github.com/Akryum/guijs/issues/34).
ref: https://wixtoolset.org/documentation/manual/v3/howtos/files_and_registry/create_start_menu_shortcut.html
> feature(tauri-bundler): add start menu shortcut on windows

- .github/workflows/release-cargo.yml
`tauri-bundler` is not in the main cargo workspace so the target directory is not in the top level. Update the publishPath to compensate.
Also removing a couple extraneous things that aren't needed either. We had an extra '/' and we don't need to bother showing the directory within the `cargo package` command.
> chore(workflow): tauri-bundler path considering workspace

- cli/tauri.js/src/helpers/spawn.ts
- cli/tauri.js/src/runner.ts
- cli/tauri.js/src/template/defaultConfig.ts
- cli/tauri.js/src/types/config.ts
sometimes we're a little bit lazy and don't want to run something to start our dev server or build our JS code, so I just implemented this config, inspired by @nothingismagick
> feat(tauri.js) add beforeDevCommand and beforeBuildCommand configs

- .github/workflows/release-npm.yml
This should add a collapsible section to the release notes for yarn audit. Sometimes yarn audit is terribly noisy, but we don't have much control over dealing with it. We still want to report, but collapse it by default so other releases are at least readable.
> chore(workflow): switch yarn audit in release to a collapsed section

- .github/workflows/release-cargo.yml
We were running into race conditions where one package depended on another being published. Limit to only allow one publish at a time, and sort based on dependencies to (hopefully) eliminate the race condition.
> chore(workflow): order cargo publish and limit to 1

- .github/workflows/release-cargo.yml
- .github/workflows/release-npm.yml
The newlines, `/n`, weren't working in our yarn audit collapse widget sequence. Switch that to empty echos.
Also the cargo publish sequence switches the installation of webkit to _after_ we check if a publish needs to be preformed. This will speed up the early exit if a package doesn't need to publish. It will be noticeable as we are now only publishing one at a time.
> chore(workflow): publish perf and prettying

- .github/workflows/release-cargo.yml
We reordered it in a previous PR, but forgot to add the `if` statement to also skip it.
> chore(workflow): skip webkit2gtk install if not publishing

- .gitignore
- Cargo.toml
- maskfile.md
As a new/first contributor, I have difficulty to check the small changes that I made is correct, especially when I want to check if it works on the [examples repo](https://github.com/tauri-apps/examples). I'm choosing [mask](https://github.com/jakedeichert/mask) because it's markdown which can be used as some sort of recipe. (also I'm more familiar with `mask` codebase)
> build(task-runner): add self-documented task runner

- cli/tauri.js/src/helpers/tauri-config.ts
If `devPath` or `distDir` is missing, throw an error that points at the docs and exit with code 1.
> fix(tauri.js): exit with code 1 if paths are missing, fixes #594

- cli/tauri.js/src/api/info.ts
When editing your `Cargo.toml`, you might clean up the `tauri = { version = "0.5.2" }` to just `tauri = "0.5"` since the inline table is kind of useless in this position.  This fix allows version shorthand.
> detect version shorthand during `tauri info`

- cli/tauri.js/src/runner.ts
This sets the headers in requests going through the `tauri dev` proxy to match what was received from the proxy target. When headers are not proxied, things like `Content-Type` not being set leads to console errors (`CONSOLE ERROR TypeError: 'text/plain' is not a valid JavaScript MIME type.`) and the application not loading the frontend assets..
> Proxy headers during `tauri dev`

- cli/tauri.js/src/runner.ts
When running with the embedded server off, `tauri dev` will still remove attributes from `<link>`s even though we are trying to run these files from the server.  This change will make sure that the attributes are not removed during dev `cfg.ctx.dev`.
> don't remove link attributes on html rewrite when in dev

- cli/tauri.js/src/api/info.ts
The `tauri info` command displays the directories in the application dir. It only displays 1 directory deep, but the function finding them recurses all subdirectories. Limiting finding directories to 1 layer deep significantly reduces time to display the folder from 9900ms to 4ms on my machine.
This change keeps the ability to recurse in the future when wanted. The current code does not use the children beyond 1 layer deep.
> Don't recurse directories while displaying tree during info command

- cli/tauri.js/src/api/info.ts
- cli/tauri.js/src/runner.ts
- cli/tauri.js/src/types/cargo.ts
As mentioned in the issue, the new possibility is multiple versions found in the lockfile. This looks like:
I marked this as non-breaking as it only changes the possible output of the `tauri info` command, which I didn't see as a non-breaking guarantee. This could break something that parses the output and strictly expects only a semver string or `"unknown"`.
> use cargo lockfile for tauri dependency during `tauri info`. close #610

- .github/workflows/release-cargo.yml
- .github/workflows/release-npm.yml
The `release-cargo` and `release-npm` workflows would not fail if `cargo publish` or `npm publish` exited with a nonzero exit code since the output was piped to `tee`. This PR uses `set -o pipefail` to ensure the correct exit code is used for the return value of the command
> fix(workflow): Fail the build if publishing has nonzero exit code

- cli/tauri.js/src/helpers/tauri-config.ts
- tauri/build.rs
`nonWebpackRequire` caches the result, so it wouldn't reflect changes on `tauri.conf.json`. Reading the file from FS and parsing it instead fixes it.
Also, `tauri` needs to rebuild to make it work.
> fix(tauri.js) properly reflect tauri.conf changes on `tauri dev`

- cli/tauri.js/src/api/info.ts
- cli/tauri.js/src/types/cargo.ts
This PR fixes the case when `tauri info` is run and a project has not yet created a `Cargo.lock`.
Closes #610. 
> fix(cli): info get tauri

- .changes/cli_info_toml_error_handling.md
- cli/tauri.js/src/api/info.ts
Expands on the fix in #674.  It will handle any error (like it did before the original change for #610) except it won't swallow them.  The original block was wrapped in an empty `try { ... } catch(_) {}` which I didn't replicate in the code replacing it.  This new fix will handle any read error for toml files, and communicate when the expected files are missing when attempted to be read.
It will also now read the manifest along with the lockfile so that it can communicate a missing manifest even if there is a lockfile.
> fix(cli): tell user of missing lockfile or manifest during info

- tauri-api/src/http.rs
This pull request will add `HttpRequestBuilder`,
described at "alternatives you've considered" section in https://github.com/tauri-apps/tauri/issues/651.
both arguments in `new` method takes `impl Into<String>` instead of `String` so you can pass url or method as `&str`, which can be helpful in various cases (e.g. when URL is already hard-coded in the codebase as `const` or `static`)
```rust
static SOME_URL: &str = "http://example.com";
let builder = HttpRequestBuilder::new("GET", SOME_URL); // I can write without clone!
```
> Implement HttpRequestBuilder for HttpRequestOptions (#651)

- .github/workflows/pr-version-updates.yml
This fixes the commit so it includes "version updates" in the text. As it is a single commit, the default squash behavior uses the commit instead of the PR title for the commit that shows up in the dev branch (which wouldn't trigger the next workflow).
> chore: fix version updates commit text

- .github/workflows/update-docs.yml
**Description**
This workflow should open a PR to `tauri-docs` with updated rust docs on ever release.
This replaces https://github.com/tauri-apps/tauri-docs/pull/78 which addresses part of https://github.com/tauri-apps/tauri-docs/issues/77.
> chore: update rust docs on release
