tauri-apps/tauri

lib/rust/Cargo.toml, lib/rust/src/api.rs, lib/rust/src/api/cmd.rs, lib/rust/src/lib.rs
=> feat(lib) open link command

lib/rust/Cargo.toml, lib/rust/src/api.rs, lib/rust/src/api/cmd.rs, lib/rust/src/command.rs, lib/rust/src/dir.rs, lib/rust/src/event.rs, lib/rust/src/file_system.rs, lib/rust/src/lib.rs, lib/rust/src/salt.rs, templates/rust/src/main.rs
=> chore(merge) feature/event-system

templates/rust/Cargo.toml
This increases our minimum required Rust version to the latest 1.37.0
=> feat(template) use the new default-run manifest field

lib/tauri.js
=> chore(entry) move <a> handling code from q-app

lib/rust/src/api.rs, lib/rust/src/api/cmd.rs, lib/rust/src/app/runner.rs, lib/tauri.js
=> fix(tauri) event system init on windows fixed

tools/rust/cargo-tauri-bundle/src/main.rs
Needed for the quasar-info command usage.
=> feat(bundle) add version to cargo-tauri-bundle subcommand

.github/workflows/test-on-pr.yml
This is following up on the discussion in #48. This PR currently builds anything with a cargo.toml as a minimal / first step check. Future steps may include building and testing against the smoke tests. Many of the builds currently fail though so not sure how we want to proceed with that. It may very well be my misunderstanding, but opening this to begin the discussion.
Here is an example of what a run will look like as it doesn't seem to have run on this PR.
https://github.com/jbolda/tauri/runs/276926274
=> Github Actions CI Process - Build Rust

.github/workflows/test-on-pr.yml
This will fix MacOS build image not having Rust installed by default.
=> install Rust stable before build

.gitignore, .npmignore, lib/rust/Cargo.toml, mode/helpers/app-paths.js, package.json, test/jest/__tests__/tauricon.spec.js
=> feat(updateWebview): and a couple npm ignores

cli/tauri.js/jest.config.js, cli/tauri.js/test/jest/__tests__/tauri.spec.js, cli/tauri.js/test/jest/__tests__/tauricon.spec.js
Fixed file paths which were changed during project reorganization
=> fix(test): fix Jest tests

cli/tauri-cli/src/bundle/path_utils.rs
I have replaced some new() functions with default() as the respective structs have only public fields. Using default instead is more expressive, I think.
=> Cleanup path_utils.rs (fix #74)

cli/tauri.js/package.json, cli/tauri.js/yarn.lock
dependency updates 
I ran the tests locally and they all continue to pass.
=> chore(upgrade): bump deps

renovate.json
Also, there is a running theory that Tuesday is a good day for upgrades.
=> schedule renovate to tone down noisiness

.github/workflows/test-on-pr.yml
This is a follow up to #105. I think the cleaner way may be to add a conditional step. This should work well (assuming the tests pass here 🤞 ). Thanks again @rajivshah3 for figuring out the issue with this originally.
=> combine jobs and add step with conditional

cli/tauri-cli/src/bundle.rs, cli/tauri-cli/src/bundle/appimage_bundle.rs, cli/tauri-cli/src/bundle/deb_bundle.rs, cli/tauri-cli/src/bundle/dmg_bundle.rs, cli/tauri-cli/src/bundle/ios_bundle.rs, cli/tauri-cli/src/bundle/osx_bundle.rs, cli/tauri-cli/src/bundle/path_utils.rs, cli/tauri-cli/src/bundle/settings.rs
=> fix(cli) improve workspace detection #67

.github/workflows/build-smoke-tests.yml
Finishing up the cache uploads by setting the ext, then caching some of the Rust items.
=> [WIP] github actions rust cache

cli/tauri.js/bin/tauri-init.js, cli/tauri.js/template.js, cli/tauri.js/templates/src-tauri/Cargo.toml
=> fix(js-cli) tauri init broken when not using the local version #135

cli/tauri.js/helpers/tauri-config.js
Checks that package.json and tauri.conf.js exist before requiring
If they don't, throw an error and exit w/ code 1
=> feat(tauri.js/tauri-config): throw error if req'd files don't exist

.github/workflows/build-smoke-tests.yml
Check cache hits before `tauri-cli` install to prevent failure when it is already installed.
=> check cache hits before install

Cargo.lock, cli/tauri-cli/Cargo.toml, cli/tauri-cli/src/bundle/wix.rs, cli/tauri-cli/src/main.rs
Removing bloat by removing Tokio dependent libraries such as Reqwest.  Also looking at alternatives for Clap and Flake2.
=> [WIP] Optimizing dependencies to remove bloat 

renovate.json
=> [WIP] Renovate to Update Examples

cli/tauri.js/runner.js
=> feat(js-cli) inject CSP from tauri.config.js

examples/gatsby/themed-site/src-tauri/Cargo.toml
=> fix(examples): Fix gatsby themed-site build errors

cli/tauri-cli/Cargo.toml
=> Update Cargo.toml to allow tests to build

cli/tauri.js/templates/src-tauri/src/main.rs
Simple proc macro at the top of the main.rs file.  Will run on production but not on normal builds.
=> [Bug fix: #204] add cfg_attr

examples/react/next.js/README.md
=> Make yarn build consistent across examples

cli/tauri.js/package.json
Adds a [`prepare` script](https://docs.npmjs.com/misc/scripts.html) to `tauri.js`. This script is run before publishing and when running `yarn` to install dependencies to ensure that the TS files are built.
=> chore(tauri.js): Add prepare script

Cargo.lock
I've installed an Atom extension called [ide-rust](https://atom.io/packages/ide-rust). It seems to keep updating the Cargo.lock, which might be out of date due to the refactor.
=> chore(tauri): Update Cargo.lock

renovate.json
=> chore(examples) add Svelte renovate group

renovate.json
=> Fix: #228 invalid JSON

cli/tauri-cli/src/bundle/appimage_bundle.rs, cli/tauri-cli/src/bundle/common.rs, cli/tauri-cli/src/bundle/deb_bundle.rs, cli/tauri-cli/src/bundle/dmg_bundle.rs, cli/tauri-cli/src/bundle/ios_bundle.rs, cli/tauri-cli/src/bundle/osx_bundle.rs, cli/tauri-cli/src/bundle/path_utils.rs, cli/tauri-cli/src/bundle/settings.rs, cli/tauri-cli/src/bundle/wix.rs, cli/tauri-cli/src/main.rs, tauri-api/src/file/extract.rs, tauri/src/app/runner.rs, tauri/src/endpoints.rs, tauri/src/event.rs, tauri/src/lib.rs, tauri/src/salt.rs, tauri/src/server.rs
Remove unwrap calls which are not helpful and expressive.  Allows the code to be a bit more self documenting and allows end user to identify where an error has occurred.
=> [Refactor] Remove unwraps from tauri

cli/tauri.js/src/api/tauricon.ts, cli/tauri.js/test/jest/__tests__/tauricon.spec.js
- Remove unnecessary awaits (the functions being called are not async/don't return promises)
- Fix png2icons import
- Avoid swallowing errors in icon generation
This test should have failed, but passed because the error was swallowed:
=> fix(tauri.js): Various fixes to tauricon.ts

cli/tauri.js/bin/tauri-build.js, cli/tauri.js/bin/tauri-dev.js, cli/tauri.js/bin/tauri-icon.js, cli/tauri.js/bin/tauri-init.js, cli/tauri.js/package.json, cli/tauri.js/src/api/build.ts, cli/tauri.js/src/api/dev.ts, cli/tauri.js/src/entry.ts, cli/tauri.js/src/runner.ts, cli/tauri.js/src/template/index.ts, cli/tauri.js/webpack.config.js, cli/tauri.js/yarn.lock
=> refactor(tauri.js) keep folder structure on /dist

cli/tauri.js/src/api/tauricon.ts, cli/tauri.js/test/jest/__tests__/tauricon.spec.js
Fixes file paths that are causing tests to fail
=> fix(tauri.js): Fix file paths in tauricon

cli/tauri.js/api.js, cli/tauri.js/templates/tauri.js, examples/vue/quasar-app/package.json, examples/vue/quasar-app/src/pages/Index.vue, tauri/src/endpoints.rs
The only problem I see here is the need to use file:// to load the tauri package, I had to do this because if I try to load the api.js file directly, it complains that I do not have the TS ESlint plugin.
=> feat(tauri.js) add API endpoint proxy, closes #197

tauri/src/app/runner.rs, tauri/src/endpoints.rs
=> fix(tauri) run setup hook after init has been eval'd

.github/workflows/smoke-test-prod.yml, .github/workflows/smoke-tests-source.yml
I believe we don't need the full standard install just to run the build.
=> use minimal profile for installation

cli/tauri.js/src/api/build.ts, cli/tauri.js/src/api/dev.ts, cli/tauri.js/src/api/info.ts, cli/tauri.js/src/api/init.ts, cli/tauri.js/src/helpers/copy-templates.ts
Replace some `require`s with `import`s, add some spaces/linebreaks here and there.
=> fix(tauri.js): eslint errors

.scripts/init_env.sh
- proper escaping
- use `!#/usr/bin/env sh` for broader compliance
=> refactor(.scripts): cleanup sh

.github/workflows/smoke-test-prod.yml, .github/workflows/smoke-tests-source.yml
Fixing the tests as we no longer have any cargo lock files.
=> chore(actions): change cache to hash on .toml

cli/tauri.js/src/template/defaultConfig.ts
=> fix(tauri.js) default CSP with the blob modifier

examples/react/create-react-app/src-tauri/tauri.conf.json, examples/react/gatsby-themed-site/src-tauri/tauri.conf.json, examples/react/next.js/src-tauri/tauri.conf.json, examples/svelte/svelte-app/src-tauri/tauri.conf.json, examples/vanillajs/monolith/src-tauri/tauri.conf.json, examples/vue/quasar-app/package.json, examples/vue/quasar-app/src-tauri/tauri.conf.json, examples/vue/quasar-app/yarn.lock, tauri-updater/Cargo.toml, tauri/test/fixture/src-tauri/tauri.conf.json
=> chore(examples) update CSP and tauri-webpack to 0.2.0

tauri/src/app/runner.rs
Properly call the onTauriInit() callback, even if it is defined after tauri is initialized.
=> fix(tauri) race condition on onTauriInit and no-server mode

renovate.json
=> chore(renovate): fix wildcard on renovate folder groups

examples/react/gatsby-themed-site/package.json, examples/react/gatsby-themed-site/src/articles/0003-third-article/index.mdx, examples/react/gatsby-themed-site/src/articles/0004-fourth-article/index.mdx, examples/react/gatsby-themed-site/src/articles/0005-fifth-article/index.mdx, examples/react/gatsby-themed-site/src/homepage/engagements/tauri-work.mdx, examples/react/gatsby-themed-site/yarn.lock
This upgrades the gatsby example deps and fixes the accidental breaking change.
=> fix(example): gatsby theme update and breaking change fix

examples/react/gatsby-themed-site/gatsby-config.js
It now requires a siteURL to function (as there isn't a great way to make it optional).
=> fix(examples): fix breaking change upstream

tauri/src/endpoints.rs
=> fix(tauri) event api not working

cli/tauri.js/src/runner.ts, examples/svelte/svelte-app/.gitignore
=> fix(tauri.js) do not inline assets on the embedded-server mode

cli/tauri.js/src/template/defaultConfig.ts
=> chore(tauri.js) default config with all API enabled and distDir fixed

cli/tauri-cli/src/bundle.rs, cli/tauri-cli/src/main.rs, cli/tauri.js/templates/src-tauri/src/build.rs
=> Feat(CLI) Icon Check fix: #309

.github/workflows/cargo-publish.yml, .github/workflows/npm-publish.yml, .github/workflows/smoke-test-prod.yml, .github/workflows/smoke-tests-source.yml, .github/workflows/test-on-pr.yml
=> Bump actions/checkout from v1 to v2

.github/workflows/greetings.yml
Just a little "hey there". For PRs remind them to sign commits.
@jbolda and I were discussing helpful messages, and the fact that we want everyone to sign their commits.
=> feat(workflows): first-timer message

cli/tauri-cli/Cargo.toml, cli/tauri-cli/src/bundle.rs, cli/tauri-cli/src/bundle/deb_bundle.rs, cli/tauri-cli/src/bundle/osx_bundle.rs, cli/tauri-cli/src/bundle/settings.rs, cli/tauri-cli/src/bundle/wix.rs, cli/tauri-cli/src/main.rs, tauri-api/src/command.rs, tauri-api/src/lib.rs, tauri/src/lib.rs
=> refactor(Bundler, API) clean up external binary logic

.github/workflows/greetings.yml
=> fix greeting message extra characters

cli/tauri.js/templates/src-tauri/Cargo.toml
=> fix(template): relax versioning for tauri

cli/tauri.js/src/entry.ts, cli/tauri.js/src/helpers/tauri-config.ts, cli/tauri.js/src/runner.ts, cli/tauri.js/src/template/defaultConfig.ts, cli/tauri.js/src/types/config.ts, cli/tauri.js/templates/mutation-observer.js, cli/tauri.js/webpack.config.js, examples/react/create-react-app/src-tauri/tauri.conf.json, examples/react/gatsby-themed-site/src-tauri/tauri.conf.json, examples/react/next.js/src-tauri/tauri.conf.json, examples/svelte/svelte-app/public/index.html, examples/svelte/svelte-app/src-tauri/tauri.conf.json, examples/vanillajs/monolith/src-tauri/tauri.conf.json, examples/vue/quasar-app/src-tauri/tauri.conf.json, examples/vue/vue-cli-app/src-tauri/tauri.conf.json, tauri/src/app/runner.rs, tauri/src/endpoints.rs
=> feat(tauri.js) inject MutationObserver to lazy load JS/CSS on no-server, add option to disable inliner

tauri/Cargo.toml, tauri/src/app/runner.rs, tauri/src/config.rs, tauri/src/endpoints.rs, tauri/src/file_system.rs, tauri/src/lib.rs
Have Error chain in all of our other libraries apart from core.  Makes sense to add it finally for a more uniform code style. This also includes adding the updater feature back into the core library to prepare it to use the new updater library.
=> Refactor(Core) add error chain

tauri/src/config.rs, tauri/src/event.rs, tauri/src/file_system.rs
=> Feature: Tests in Core

tauri/src/file_system.rs
=> Bug(core): fix tests

cli/tauri.js/templates/src-tauri/Cargo.toml
=> change serde versions to 1.0

cli/tauri.js/.eslintrc.js, cli/tauri.js/src/api/build.ts, cli/tauri.js/src/api/dev.ts, cli/tauri.js/src/api/info.ts, cli/tauri.js/src/api/tauricon.ts, cli/tauri.js/src/helpers/logger.ts, cli/tauri.js/src/helpers/spawn.ts, cli/tauri.js/src/helpers/tauri-config.ts, cli/tauri.js/src/template/index.ts, cli/tauri.js/src/types/config.ts
Fixes ESLint errors and suppresses various rules. I'm happy to change the rules to fit everyone else's preferences though
=> refactor(tauri.js): Fix ESLint errors

cli/tauri.js/templates/tauri.js, examples/vue/quasar-app/src-tauri/src/main.rs, tauri/src/app.rs, tauri/src/app/runner.rs, tauri/src/lib.rs
=> feat(tauri) add splashscreen API

cli/tauri-bundler/Cargo.toml, cli/tauri.js/package.json, cli/tauri.js/templates/src-tauri/Cargo.toml, tauri-api/Cargo.toml, tauri-updater/Cargo.toml, tauri-utils/Cargo.toml, tauri/Cargo.toml
=> chore(release): version updates

.github/workflows/release-cargo.yml, .github/workflows/release-npm.yml
=> fix(publish): login and build

.github/workflows/release-cargo.yml, .github/workflows/release-npm.yml
=> fix(publish): attempt two

.github/workflows/release-cargo.yml
=> fix(publish): add missing $

.github/workflows/release-cargo.yml, .github/workflows/release-npm.yml
=> fix(publish): touch up npm/cargo publish workflow

cli/tauri.js/package.json
update template on npm and release
=> chore(release:npm) version updates

.github/workflows/smoke-tests-source.yml, cli/tauri-bundler/src/bundle/wix.rs
Not able to compile MSI using a x86 architecture.
=> Bug(Bundler): fix target arch in wix

cli/tauri.js/templates/tauri.js
=> fix(tauri.js) if the DOM is already loaded, listen for <a> clicks

cli/tauri.js/templates/tauri.js
=> fix(open) open <a> on browser only if target=_blank

cli/tauri-bundler/src/bundle/osx_bundle.rs, cli/tauri-bundler/src/bundle/settings.rs
=> feat(bundler) add exception_domain option by @nothingismagick

cli/tauri-bundler/src/bundle/deb_bundle.rs, cli/tauri-bundler/src/bundle/osx_bundle.rs
=> fix(bundler) expose environment variables to GUI apps on linux and mac

.github/workflows/release-cargo.yml, .github/workflows/release-npm.yml
Bumping the tangle github action version as a new one has been published and it comes with more logging.
=> chore(workflow): update tangle release for more logging

cli/tauri-bundler/Cargo.toml, cli/tauri.js/package.json, tauri-api/Cargo.toml, tauri/Cargo.toml
=> chore(updates) version updates

.github/workflows/release-cargo.yml
just put it in everything for now
=> fix(workflow): runner has to be in steps

cli/tauri.js/package.json
=> [version updates]: tauri.js bad postinstall

.gitignore, .scripts/batch_to_exe.cmd, cli/tauri.js/templates/tauri.js, tauri-api/src/command.rs
=> Fix(All) - Add Edge support to GUIJS 

tauri/src/endpoints.rs, tauri/src/endpoints/cmd.rs
=> Revert "fix: #377 window.tauri is undefined upon reloading"

.github/workflows/build-smoke-tests.yml
Changes in the Tauri repo meant that we don't build on install, so we need to manually do it now.
=> chore(workflow): build tauri.js after install

.github/workflows/check-on-push.yml
This relies on the `setup-node` action, which installs problem matchers for `eslint` so that GitHub can report any ESLint errors
=> feature(workflows): Add ESLint check to workflow

README.md
=> chore: fix missing links in some badges

cli/tauri-bundler/Cargo.toml, cli/tauri.js/package.json, tauri-api/Cargo.toml, tauri-updater/Cargo.toml, tauri-utils/Cargo.toml, tauri/Cargo.toml
=> [version updates] Merge Windows Related Changes

cli/tauri-bundler/Cargo.toml, cli/tauri.js/package.json, tauri-api/Cargo.toml, tauri-updater/Cargo.toml, tauri-utils/Cargo.toml, tauri/Cargo.toml
=> [update versions] minor fix

tauri-api/Cargo.toml
=> Revert "[version updates] minor fix"

cli/tauri-bundler/Cargo.toml, cli/tauri.js/package.json, tauri-api/Cargo.toml, tauri-updater/Cargo.toml, tauri-utils/Cargo.toml, tauri/Cargo.toml
=> [version updates] Core create release

cli/tauri-bundler/src/bundle/deb_bundle.rs, cli/tauri-bundler/src/bundle/settings.rs
=> fix(bundler) throw error when resource, external bin or icon not found

cli/tauri-bundler/Cargo.toml, cli/tauri-bundler/src/bundle.rs, cli/tauri-bundler/src/bundle/settings.rs, cli/tauri-bundler/src/bundle/tauri_config.rs, cli/tauri-bundler/src/main.rs, cli/tauri.js/src/template/defaultConfig.ts, cli/tauri.js/templates/src-tauri/Cargo.toml
=> feature(bundle) merge BundleSettings with config from tauri.conf.json > tauri > bundle

cli/tauri-bundler/src/bundle/settings.rs, cli/tauri-bundler/src/bundle/templates/main.wxs, cli/tauri-bundler/src/main.rs, tauri-api/src/command.rs, tauri/build.rs, tauri/src/endpoints.rs, tauri/src/lib.rs
=> Refact(All): (WIP) Cleanup workflow and add Windows Features. 

cli/tauri-bundler/Cargo.toml
=> [version updates] CLI to 0.4.3

cli/tauri.js/templates/src-tauri/Cargo.toml
=> fix(template) incorrect package > authors field on Cargo.toml

cli/tauri.js/templates/tauri.js, tauri/src/app/runner.rs, tauri/src/endpoints.rs, tauri/src/lib.rs
=> fix(tauri) do not use template literals and fix entry for IE

cli/tauri-bundler/src/bundle/templates/main.wxs, cli/tauri-bundler/src/bundle/wix.rs
=> feat(Bundler) Add Update, UI and Custom Install Dir

cli/tauri-bundler/Cargo.toml, cli/tauri.js/package.json, tauri/Cargo.toml
=> chore(release): remaining windows fixes [version updates]

tauri/Cargo.toml
=> Chore(Tauri): fix docs.rs

cli/tauri.js/bin/tauri-build.js, cli/tauri.js/src/runner.ts
=> feat(tauri.js) expose target arg to `tauri build`

cli/tauri-bundler/src/bundle/settings.rs
=> fix(bundler) do not require [package.metadata.bundle] for tauri projects

cli/tauri.js/bin/tauri-dev.js, cli/tauri.js/src/runner.ts, cli/tauri.js/src/types/config.ts
=> feat(tauri.js) keep running on failures & watch tauri lib on contribs

cli/tauri-bundler/src/bundle/settings.rs
=> feat(bundler) bail if can't parse tauri config

cli/tauri.js/src/template/defaultConfig.ts, cli/tauri.js/test/jest/fixtures/app-test-setup.js, tauri/examples/communication/src-tauri/Cargo.toml, tauri/src/app/runner.rs, tauri/src/config.rs
=> feat(config) expose "fullscreen" property, closes #488

cli/tauri.js/src/runner.ts, cli/tauri.js/templates/tauri.js, tauri/examples/communication/dist/communication.js, tauri/examples/communication/dist/fs.js, tauri/examples/communication/dist/index.html, tauri/examples/communication/dist/index.tauri.html, tauri/examples/communication/dist/window.js
=> feat(example) add API showcase to communication example

cli/tauri.js/api/dialog.js, cli/tauri.js/templates/tauri.js, tauri-api/Cargo.toml, tauri-api/src/dialog.rs, tauri-api/src/lib.rs, tauri/Cargo.toml, tauri/examples/communication/dist/dialog.js, tauri/examples/communication/dist/index.html, tauri/examples/communication/dist/index.tauri.html, tauri/src/endpoints.rs, tauri/src/endpoints/cmd.rs, tauri/src/endpoints/dialog.rs, tauri/src/lib.rs
=> feat(tauri) add dialog API

cli/tauri-bundler/Cargo.toml, tauri-api/Cargo.toml, tauri-updater/Cargo.toml, tauri-utils/Cargo.toml, tauri/Cargo.toml
=> Chore(release): [version updates] update to core, updater, utils, api and bundler

README.md
=> chore: update readme with new rust packages

cli/tauri-bundler/src/bundle/settings.rs
=> fix(bundler) properly show error message for tauri config

cli/tauri-bundler/Cargo.toml, cli/tauri.js/package.json, tauri-api/Cargo.toml, tauri-updater/Cargo.toml, tauri-utils/Cargo.toml, tauri/Cargo.toml
=> chore(tauri) bump versions to 0.5.0 (#532) version updates

cli/tauri.js/yarn.lock
This fixes the vulnerability in https://github.com/kevva/decompress. (see [here](https://github.com/kevva/decompress/pull/73) for the pull request).
=> Updated the dependencies (and fixed the decompress vulnerability)

cli/tauri.js/package.json, cli/tauri.js/templates/src-tauri/Cargo.toml
=> chore(tauri.js) version updates

cli/tauri.js/api/dialog.js, cli/tauri.js/api/event.js, cli/tauri.js/api/fs/index.js, cli/tauri.js/api/process.js, cli/tauri.js/api/window.js
=> docs(api) fix JSDoc types

cli/tauri-bundler/Cargo.toml, cli/tauri-bundler/src/bundle.rs, cli/tauri-bundler/src/bundle/appimage_bundle.rs, cli/tauri-bundler/src/bundle/deb_bundle.rs, cli/tauri-bundler/src/bundle/dmg_bundle.rs, cli/tauri-bundler/src/bundle/ios_bundle.rs, cli/tauri-bundler/src/bundle/osx_bundle.rs, cli/tauri-bundler/src/bundle/settings.rs, cli/tauri-bundler/src/bundle/tauri_config.rs, cli/tauri-bundler/src/main.rs, cli/tauri.js/src/runner.ts, cli/tauri.js/src/template/defaultConfig.ts, cli/tauri.js/src/types/config.ts
=> feat(tauri) bundle formats config on tauri.js, fix bundler appimage

cli/tauri.js/yarn.lock
=> chore(tauri.js): Sync lockfile

cli/tauri.js/api/fs/index.js
Seems a refactor forgot to reassign the import location of tauri.js
=> fix(tauri.js): api tauri import

cli/tauri.js/package.json
=> chore(tauri.js): version updates

cli/tauri-bundler/src/bundle.rs, cli/tauri-bundler/src/bundle/appimage_bundle.rs
=> fix(bundler) bundle deb and appimage simultaneously correctly

.github/workflows/pr-to-master.yml
We can better manage the security by running from the forked version and selectively keeping in sync with upstream.
=> chore: switched to forked create-pull-request

tauri/Cargo.toml
=> feat(tauri): Move tiny_http behind feature flag, close #549

cli/tauri-bundler/src/bundle/deb_bundle.rs, cli/tauri-bundler/src/bundle/osx_bundle.rs, cli/tauri-bundler/src/bundle/settings.rs, cli/tauri-bundler/src/bundle/tauri_config.rs, cli/tauri.js/src/helpers/tauri-config.ts, cli/tauri.js/src/template/defaultConfig.ts, cli/tauri.js/src/types/config.ts
=> feat(bundler) move deb & OSX bootstrappers behind config flag, closes #527

cli/tauri.js/src/helpers/spawn.ts, cli/tauri.js/src/runner.ts
=> fix(tauri.js) beforeDevCommand an beforeBuildCommand cwd as appDir

README.md
Add space after comma as I believe this should be more correct and look neater.
=> Put space after comma in README

cli/tauri-bundler/Cargo.toml, cli/tauri.js/package.json, tauri/Cargo.toml
=> chore(tauri) version updates (bundler & tauri.js 0.6.0, tauri 0.5.1)

cli/tauri.js/api/http.js, cli/tauri.js/templates/tauri.js, tauri-api/Cargo.toml, tauri-api/src/http.rs, tauri-api/src/lib.rs, tauri/examples/communication/dist/http.js, tauri/examples/communication/dist/index.html, tauri/examples/communication/dist/index.tauri.html, tauri/examples/communication/src-tauri/src/cmd.rs, tauri/examples/communication/src-tauri/src/main.rs, tauri/src/app.rs, tauri/src/app/runner.rs, tauri/src/endpoints.rs, tauri/src/endpoints/cmd.rs, tauri/src/endpoints/dialog.rs, tauri/src/endpoints/file_system.rs, tauri/src/endpoints/http.rs, tauri/src/lib.rs
=> feat(tauri) add httpRequest API

cli/tauri.js/package.json, cli/tauri.js/src/helpers/net.ts, cli/tauri.js/src/runner.ts, cli/tauri.js/yarn.lock
=> hotfix(tauri.js) proxy dev-server websocket connection so HMR works

tauri/examples/communication/src-tauri/tauri.js
I tried to build the project start with script in `.script`. But it would still say `.../src-tauri/tauri.js No such file or directory`. Bring a copy here should be able to build without any problem.
=> fix(tauri) add missing file in example

tauri/Cargo.toml
=> chore(versions) update tauri to 0.5.2 [version updates]

cli/tauri.js/package.json
=> chore(versions) update tauri.js to 0.6.2 [version updates]

README.md
=> feat(readme): update for new docs relaunch

tauri-api/Cargo.toml
=> chore(api): "version updates"

maskfile.md
=> feat(build) Add Powershell support to the maskfile. 

cli/tauri-bundler/src/main.rs
When the bundler was changed so that icons were specified in `tauri.conf.json` instead of `Cargo.toml`, the error message was not updated
=> fix(bundler): Update missing icon error message

cli/tauri.js/src/runner.ts
=> move tauri.js injection to <head>. Fixes #625

tauri/src/app/runner.rs, tauri/src/endpoints.rs, tauri/src/endpoints/cmd.rs, tauri/src/endpoints/dialog.rs, tauri/src/endpoints/file_system.rs, tauri/src/endpoints/http.rs
=> fix(tauri) no-server mode should read html with include_str macro closes #633

cli/tauri-bundler/src/bundle/dmg_bundle.rs
`CI=true` will prevent the DMG process to fail. (CI mode)
=> fix(bundler): Prevent CI to fail on macos (#592)

cli/tauri-bundler/src/bundle/templates/appimage
Closes #601.
Thanks to @alvarohm for providing the fix.
=> fix(appimage): various fix: #601

cli/tauri.js/src/api/info.ts, cli/tauri.js/src/api/tauricon.ts, cli/tauri.js/tsconfig.json
Resolves `eslint` error "require statement not part of an import statement"
=> chore(tauri.js): Resolve eslint errors

cli/tauri.js/src/helpers/spawn.ts, cli/tauri.js/src/runner.ts, tauri/src/app/runner.rs
=> fix(tauri) dev crashes when server not running, path not found, multiple app instances on HMR

cli/tauri.js/src/api/info.ts, cli/tauri.js/src/entry.ts, cli/tauri.js/src/helpers/tauri-config.ts, cli/tauri.js/src/runner.ts, cli/tauri.js/src/types/cargo.ts, tauri/Cargo.toml, tauri/src/app/runner.rs
https://github.com/Boscop/web-view/issues/189
=> fix(tauri) use web-view fork to fix windows build on SDK 10.0.19041.1

tauri/Cargo.toml, tauri/src/event.rs
=> fix(tauri) allow registering events outside of the main thread

cli/tauri-bundler/Cargo.toml, cli/tauri.js/package.json, tauri-api/Cargo.toml, tauri-utils/Cargo.toml, tauri/Cargo.toml
=> chore(tauri) version updates

.github/workflows/release-cargo.yml, .github/workflows/release-npm.yml
=> fix(workflow): Change node and update gh-tangle-release to 0.6.2

tauri/Cargo.toml
cargo publish failed because of this
=> fix(tauri) add version to web-view git deps

.github/workflows/pr-to-master.yml
Hopefully this will fix our random permission failure :(
=> chore: bump PR action version to v2.8.0

.changes/config.json, .changes/readme.md, .github/workflows/change-status-on-PR.yml
This PR implements the shell around covector.
Note: It looks like it errors if we don't have any changes on `status`. Will get a fix in today for that, but it will be good to get this folder in so we can start adding in changes.
=> feature: implement covector

.github/workflows/build-smoke-tests.yml
We are turning off the smoke tests for the time being as they are eating up our runners to much relative to the value we are currently getting from them. We will enable them in the future in a way that makes better use of our resources.
=> chore: turn off smoke tests

cli/tauri.js/src/runner.ts
=> fix(tauri.js) kill beforeDevProcess on shutdown

cli/tauri.js/src/runner.ts
=> fix(tauri.js) regression on hot reload when Rust doesn't compile

.changes/HttpRequestBuilder-implementation.md, .changes/config.json, .changes/kill-beforeDevProcess-on-shutdown.md, .changes/readme.md, .changes/reflect-conf-changes.md, .changes/tauri-hot-reload-regression.md, .changes/tauri-info-crash.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr-to-master.yml, .github/workflows/pr-version-updates.yml
**Description**
This PR implements an action that will run `covector version` on a merge to the `dev` branch. After it runs, it will open up (or update an existing) PR with the version changes implemented. To kick off publishing of packages, the PR needs only to be merged which will invoke the next PR to open targeting the master branch and the publishing sequence.
This also includes readme updates at suggested by @chippers. Thanks!
=> feature: implement version change PR

.changes/appimage_fix.md, cli/tauri-bundler/src/bundle/appimage_bundle.rs, cli/tauri-bundler/src/bundle/templates/appimage
=> fix(tauri) use appimagetool to build, finish script run, proper AppRun

.github/workflows/build-smoke-tests.yml, .github/workflows/test-on-pr.yml
*description*
This turns on the RUSTBACKTRACE that we can get more information from the CI logs when an error occurs.
This closes #663.
=> chore: rustbacktrace on [#663]

.changes/no-server-fix.md, tauri-api/Cargo.toml, tauri-api/build.rs, tauri-api/src/cli/macros.rs, tauri-api/src/config.rs, tauri-utils/src/lib.rs, tauri-utils/src/process.rs, tauri/build.rs, tauri/src/app/runner.rs, tauri/src/endpoints.rs
Fixes no-server mode not running on another machine due to fs::read_to_string usage instead of the include_str macro.
Build no longer fails when compiling without environment variables, now the app will show an error.
=> fix(tauri) environment variables usage

cli/tauri.js/src/types/config.ts, tauri-api/src/cli.rs, tauri-api/src/config.rs
=> feat(tauri) CLI args additions (positional args, bool as value for args with takesValue=false)

.github/workflows/release-cargo.yml
=> chore: generate the Cargo lockfile for audit to run

cli/tauri.js/package.json, cli/tauri.js/src/template/index.ts, cli/tauri.js/webpack.config.js, cli/tauri.js/yarn.lock
=> feat(tauri.js) automatically detect current tauri version for template

tauri-api/Cargo.toml
=> fix(tauri-api) use published tauri-dialog

tauri-api/src/http.rs, tauri/src/endpoints/http.rs
=> fix(tauri) httpRequest API JSON/Text response reader, header value as string, closes #691

tauri/Cargo.toml
The #657 fix wasn't complete because it uses a git dependency, which is ignored when publishing.
=> fix(tauri) use forked web-view and webview-sys

.github/workflows/change-status-on-PR.yml, .github/workflows/pr-version-updates.yml
**Description**
Covector branch moved to main. Update workflows to target main branch.
=> fix: covector action should ref main now

.changes/bundler-check-mksquashfs.md, cli/tauri-bundler/src/bundle/appimage_bundle.rs
Checks if mksquashfs is installed before bundling AppImage
Fixes #706
=> fix(bundler): Check if mksquashfs is installed before bundling AppImage, fix: #706

.changes/fs-read-dir-api.md, cli/tauri.js/api-src/types/fs.ts, tauri-api/Cargo.toml, tauri-api/src/dir.rs, tauri-api/src/dir/utils.rs, tauri/src/endpoints/file_system.rs
the readDir API isn't very useful right now, it's complicated to use. This PR transforms the API result to something more like the standard FS API out there.
=> refactor(api) rewrite readDir API

tauri-api/src/dialog.rs, tauri-api/src/file.rs, tauri-api/src/notification.rs, tauri-api/src/path.rs, tauri/src/endpoints.rs, tauri/src/endpoints/cmd.rs, tauri/src/endpoints/file_system.rs, tauri/src/endpoints/notification.rs, tauri/src/endpoints/salt.rs, tauri/src/event.rs, tauri/src/settings.rs
=> refactor(tauri) simplify API functions types usage

.changes/bundler-binaries.md, cli/tauri-bundler/src/bundle.rs, cli/tauri-bundler/src/bundle/appimage_bundle.rs, cli/tauri-bundler/src/bundle/common.rs, cli/tauri-bundler/src/bundle/deb_bundle.rs, cli/tauri-bundler/src/bundle/ios_bundle.rs, cli/tauri-bundler/src/bundle/msi_bundle.rs, cli/tauri-bundler/src/bundle/osx_bundle.rs, cli/tauri-bundler/src/bundle/settings.rs, cli/tauri-bundler/src/bundle/templates/main.wxs, cli/tauri-bundler/src/bundle/wix.rs, cli/tauri-bundler/src/main.rs
=> feat(bundler) bundle all binaries from the project

cli/tauri-bundler/src/bundle.rs, cli/tauri-bundler/src/bundle/appimage_bundle.rs, cli/tauri-bundler/src/bundle/common.rs, cli/tauri-bundler/src/bundle/dmg_bundle.rs, cli/tauri-bundler/src/bundle/templates/appimage, cli/tauri-bundler/src/bundle/wix.rs
=> chore(bundler) show scripts output

cli/tauri.js/api-src/notification.ts, cli/tauri.js/api-src/types/notification.ts, cli/tauri.js/rollup.config.js, cli/tauri.js/templates/tauri.js
=> fix(tauri.js) move Notification initialization to tauri.js script

.github/workflows/change-status-on-PR.yml, .github/workflows/pr-version-updates.yml
**Description**
Pin the covector action rather than rely on the master branch.
=> chore: pin covector action

cli/tauri.js/package.json, cli/tauri.js/yarn.lock
=> feat(tauri.js) add TS API definition files (.d.ts)
